### ISSUE TITLE
Moving some sliders affects other sliders' values

### ISSUE THREAD

**Issue by Cam9731** [kylergib/WaveLinkPluginTouchPortal#16]
Hello,

First off, thanks for making this, It's a fantastic plugin and something I've been waiting for since I first got my Wave 3.

The only issue I have is that on making certain sliders on a page and moving those sliders, the values of other unrelated sliders sometimes gets affected as well. For example, if I have a slider for my browser, changing that also effects the level of the slider for my discord. This is purely a visual change, the modification isn't reflected within wave link, but it does get my sliders out of sync with what wave link is showing me. This bug/issue is present on the example page provided as well.

Is there a way to link/unlink sliders from touchportal that I'm not seeing? Is this in any way related to being able to "link" the stream/local levels within wavelink itself?

I appreciate any input and thanks again for making this awesome plugin.

(Not sure if this gif attached properly but it shows what I'm talking about)

![20230813_173752](https://github.com/kylergib/WaveLinkPluginTouchPortal/assets/55032379/a219e128-1346-4b14-a527-bd3c7413d88f)

**Comment by kylergib** [comment]
Hi, this is a known issue with Touch Portal itself. unsure if you are in the touch portal discord, but when it happens if you refresh the page it should fix. sometimes i have to restart the app on my ipad for it to fix fully. 

Below is a screen shot of the known issue from the touch portal discord. 
![Screenshot 2023-08-13 at 6 45 51 PM]
(https://github.com/kylergib/WaveLinkPluginTouchPortal/assets/48994502/0394a4e3-d495-4d6b-b56f-2bf9b59b5187)

**Comment by Cam9731** [comment]
Wow, thanks for the quick response!

I haven't played around with sliders prior to this, good to know that this is a known issue in TP.

Only tangentially related, but do you have any plans to implement functionality pertaining to the linking functionality within WaveLink itself, like how you can link the values of Stream/Local? Is there a way within touch portal to purposefully influence the values of other sliders?

**Comment by kylergib** [comment]
im sorry, but i do not fully understand your question lol can you re explain and/or give me an example? lol

**Comment by Cam9731** [comment]
Sure, no problem.

![image](https://github.com/kylergib/WaveLinkPluginTouchPortal/assets/55032379/3d86b08c-8c87-45e3-b414-a96870bf2160)

So in this image, the Stream and Local volumes are linked, meaning within wavelink if I move just one of the volume sliders, the other one will move relative to its position. This functionality already works within your plugin from a functional standpoint, but not visually.

![20230813_180930](https://github.com/kylergib/WaveLinkPluginTouchPortal/assets/55032379/1a4c1cb4-8c46-4589-a0d4-be5edace49b5)

So essentially, within your plugin, if I move the "System - Local" slider both will change in WaveLink. Visually in TP only the slider for the "System - Local" source will be updated, but in WaveLink the value for Stream was changed as well.

![20230813_181405](https://github.com/kylergib/WaveLinkPluginTouchPortal/assets/55032379/a1090113-8e0e-4805-9cfd-731f59348d80)

I'm wondering if it is possible to intentionally link the sliders in TP somehow so that if the sources are linked within WaveLink like in my first image, then the values of both sliders in TP would change when one of them is modified.

**Comment by kylergib** [comment]
ah i understand. i think i fixed it. when i first made the plugin any changes you made in wave link itself also updated the sliders on touch portal. that broke when update 1.8 came out and elgato changed a bunch of their stuff. i think i fixed. here is an update if you dont mind trying it and letting me know if it fixes for you as well. when you add it into touch portal the version should say 1102 if you import the new one. 

[WaveLinkPlugin.zip](https://github.com/kylergib/WaveLinkPluginTouchPortal/files/12330665/WaveLinkPlugin.zip)

**Comment by Cam9731** [comment]
PERFECT! Not only does that achieve the functionality I described above, but that also seems to mitigate the issue with unrelated sliders being affected, at least within my configuration. Thank you so much!

**Comment by kylergib** [comment]
Sweet. Glad it worked! Closing the issue now. With PR https://github.com/kylergib/WaveLinkPluginTouchPortal/pull/17
